" be improved, required
set nocompatible

" 
if filereadable(expand("~/.vim/basic.vim"))
    source ~/.vim/basic.vim
endif

if filereadable(expand("~/.vim/plugin.vim"))
    source ~/.vim/plugin.vim
endif

if filereadable(expand("~/.vim/keymap.vim"))
    source ~/.vim/keymap.vim
endif
